options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'maven:3.9.6-eclipse-temurin-17'
    entrypoint: 'bash'
    args: 
        - '-c'
        - |-
          SNYK_TOKEN=${_SNYK_TOKEN}
          export SNYK_TOKEN
          mvn snyk:test -fn 
    id: Snyk SCA
