options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'ubuntu'
    entrypoint: 'mvn'
    args: 
        - '-c'
        - |-
          apt-get update
          apt-get -y install maven 
          SNYK_TOKEN=${_SNYK_TOKEN}
          export SNYK_TOKEN
          mvn snyk:test -fn 
    id: Snyk SCA
